// Domain types — mirror the Rust structs in commands/project.rs.
// All fields are snake_case to match Tauri's camelCase serialisation rules
// (Tauri converts Rust snake_case → camelCase automatically via serde).

export type SegmentStatus =
  | "untranslated"
  | "translated"
  | "reviewed"
  | "needs_review";

export interface Project {
  id: string;
  name: string;
  engine: string;
  gamePath: string;
  createdAt: string;
  updatedAt: string;
}

export interface OpenProjectResult {
  project: Project;
  wasRestored: boolean;
}

export interface SourceFile {
  id: string;
  projectId: string;
  fileName: string;
  filePath: string;
  fileType: string;
  translationSecs: number | null;
  /** Segments with status 'translated' (strict — needs_review not included). */
  translatedCount: number;
  /** Segments with status 'needs_review' (remaining review work). */
  needsReviewCount: number;
  totalCount: number;
}

export interface FontScanResult {
  existingFontCount: number;
  totalTranslated: number;
  engine: string;
}

export interface ProjectStats {
  fileCount: number;
  totalSegments: number;
  untranslatedCount: number;
  translatedCount: number;
  needsReviewCount: number;
  /** With the other three counters, the four statuses sum to totalSegments. */
  reviewedCount: number;
}

export interface Segment {
  id: string;
  sourceFileId: string;
  jsonKey: string;
  sourceText: string;
  targetText: string;
  status: SegmentStatus;
  qaScore: number | null;
  createdAt: string;
  updatedAt: string;
}

/// One segment's `target_text`/`status` as just persisted to the DB.
/// Emitted as part of `h2s://llm/segments-updated` (one event per batch).
export interface SegmentUpdate {
  id: string;
  targetText: string;
  status: SegmentStatus;
}

export interface PaginatedSegments {
  items: Segment[];
  total: number;
  page: number;
  pageSize: number;
}

/** Which segment column(s) a project-wide search matches against. */
export type SearchScope = "both" | "source" | "target";

/** One project-wide search hit — a segment plus its file's name for grouping. */
export interface SegmentSearchHit extends Segment {
  fileName: string;
}

export interface SegmentSearchResult {
  items: SegmentSearchHit[];
  /** Real match count — `items` is capped server-side (500). */
  total: number;
}

// ---------------------------------------------------------------------------
// TM
// ---------------------------------------------------------------------------

export interface TmEntry {
  id: string;
  sourceHash: string;
  sourceText: string;
  targetText: string;
  engine: string;
  langPair: string;
  confidence: number;
  createdAt: string;
}

export interface TmSuggestion {
  entry: TmEntry;
  score: number;
  matchType: "exact" | "fuzzy";
}

// ---------------------------------------------------------------------------
// QA
// ---------------------------------------------------------------------------

export type QaErrorType =
  | { type: "missing_placeholder"; placeholder: string }
  | {
      type: "line_too_long";
      line: number;
      units: number;
      max_units: number;
      char_count: number;
    }
  | { type: "bom_detected" };

export interface QaResult {
  score: number;
  errors: QaErrorType[];
}

export interface QaReport {
  totalSegments: number;
  okCount: number;
  errorCount: number;
  errorsByType: Record<string, number>;
}

// ---------------------------------------------------------------------------
// Glossary
// ---------------------------------------------------------------------------

export interface GlossaryTerm {
  id: string;
  sourceText: string;
  targetText: string;
  langPair: string;
  domain: string;
  projectId: string | null;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

/** Payload of the `h2s://glossary/extraction-done` event. */
export interface GlossaryExtractionDonePayload {
  projectId: string;
  terms: GlossaryTerm[];
  error: string | null;
}

// ---------------------------------------------------------------------------
// .h2s exchange pack (share/resume a translation)
// ---------------------------------------------------------------------------

export interface PackExportSummary {
  segmentCount: number;
  fileCount: number;
  glossaryCount: number;
  tmCount: number;
}

/** Hard reason why a pack cannot be imported (typed by the backend). */
export type ImportBlocker =
  | { type: "notAPack" }
  | { type: "unsupportedVersion"; version: number }
  | { type: "engineMismatch"; packEngine: string; projectEngine: string }
  | { type: "langPairMismatch"; packLangPair: string; projectLangPair: string }
  | { type: "invalidPack"; detail: string };

/** Dry-run result of `preview_h2s_import` — nothing has been written. */
export interface ImportPreview {
  blocker: ImportBlocker | null;
  packGameTitle: string;
  packAppVersion: string;
  packCreatedAt: string;
  titleMismatch: boolean;
  applicable: number;
  identical: number;
  conflicts: number;
  sourceChanged: number;
  orphans: number;
  glossaryCount: number;
  tmCount: number;
}

/** Collision policy of `apply_h2s_import`. */
export type ImportPolicy =
  | "fill"
  | "overwrite_except_reviewed"
  | "overwrite_all";

/** Final report of `apply_h2s_import` (also the `h2s://project/import-done` payload). */
export interface ImportReport {
  applied: number;
  appliedSourceChanged: number;
  skippedConflicts: number;
  skippedSourceChanged: number;
  identical: number;
  orphans: number;
  glossaryAdded: number;
  glossaryConflicts: number;
  tmAdded: number;
  backupPath: string;
}

// ---------------------------------------------------------------------------
// LLM
// ---------------------------------------------------------------------------

export interface ProviderConfig {
  url: string;
  model: string;
  apiKey?: string;
  batchSize: number;
}
