// Domain types — mirror the Rust structs in commands/project.rs.
// All fields are snake_case to match Tauri's camelCase serialisation rules
// (Tauri converts Rust snake_case → camelCase automatically via serde).

export type SegmentStatus =
  | "untranslated"
  | "translated"
  | "reviewed"
  | "needs_review";

export interface Project {
  id: string;
  name: string;
  engine: string;
  gamePath: string;
  createdAt: string;
  updatedAt: string;
}

export interface OpenProjectResult {
  project: Project;
  wasRestored: boolean;
}

export interface SourceFile {
  id: string;
  projectId: string;
  fileName: string;
  filePath: string;
  fileType: string;
  translationSecs: number | null;
  translatedCount: number;
  totalCount: number;
}

export interface FontScanResult {
  existingFontCount: number;
  totalTranslated: number;
  engine: string;
}

export interface ProjectStats {
  fileCount: number;
  totalSegments: number;
  untranslatedCount: number;
  translatedCount: number;
  needsReviewCount: number;
}

export interface Segment {
  id: string;
  sourceFileId: string;
  jsonKey: string;
  sourceText: string;
  targetText: string;
  status: SegmentStatus;
  qaScore: number | null;
  createdAt: string;
  updatedAt: string;
}

/// One segment's `target_text`/`status` as just persisted to the DB.
/// Emitted as part of `h2s://llm/segments-updated` (one event per batch).
export interface SegmentUpdate {
  id: string;
  targetText: string;
  status: SegmentStatus;
}

export interface PaginatedSegments {
  items: Segment[];
  total: number;
  page: number;
  pageSize: number;
}

// ---------------------------------------------------------------------------
// TM
// ---------------------------------------------------------------------------

export interface TmEntry {
  id: string;
  sourceHash: string;
  sourceText: string;
  targetText: string;
  engine: string;
  langPair: string;
  confidence: number;
  createdAt: string;
}

export interface TmSuggestion {
  entry: TmEntry;
  score: number;
  matchType: "exact" | "fuzzy";
}

// ---------------------------------------------------------------------------
// QA
// ---------------------------------------------------------------------------

export type QaErrorType =
  | { type: "missing_placeholder"; placeholder: string }
  | {
      type: "line_too_long";
      line: number;
      units: number;
      max_units: number;
      char_count: number;
    }
  | { type: "bom_detected" };

export interface QaResult {
  score: number;
  errors: QaErrorType[];
}

export interface QaReport {
  totalSegments: number;
  okCount: number;
  errorCount: number;
  errorsByType: Record<string, number>;
}

// ---------------------------------------------------------------------------
// Glossary
// ---------------------------------------------------------------------------

export interface GlossaryTerm {
  id: string;
  sourceText: string;
  targetText: string;
  langPair: string;
  domain: string;
  projectId: string | null;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// LLM
// ---------------------------------------------------------------------------

export interface ProviderConfig {
  url: string;
  model: string;
  apiKey?: string;
  batchSize: number;
}
